all:
  hosts:
    node1:
      ansible_host: 104.248.87.135
      ip: 104.248.87.135
      access_ip: 104.248.87.135
    node2:
      ansible_host: 134.209.80.172
      ip: 134.209.80.172
      access_ip: 134.209.80.172
    node3:
      ansible_host: 134.209.95.147
      ip: 134.209.95.147
      access_ip: 134.209.95.147
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
