all:
  hosts:
    node1:
      ansible_host: 159.223.1.35
      ip: 159.223.1.35
      access_ip: 159.223.1.35
    node2:
      ansible_host: 164.92.154.160
      ip: 164.92.154.160
      access_ip: 164.92.154.160
    node3:
      ansible_host: 146.190.31.230
      ip: 146.190.31.230
      access_ip: 146.190.31.230
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
